# Generated by Django 2.0.4 on 2018-05-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentQuery',
            fields=[
                ('fbId', models.TextField(primary_key=True, serialize=False)),
                ('queryId', models.TextField(default=None, null=True)),
            ],
        ),
    ]
